server:
  port: 8082
spring:
  application:
    name: ORDER-SERVICE
  profiles:
    active: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-57924009.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: Internal
            client-id: 0oaghtzl7n5ke4Zc55d7
            client-secret: ICHbcjKYp2QwJmIn43opu3g6wZiwzthE008FjlQz0KiRyA9KxfTyxxm3KZhOzm7x
        provider:
          okta:
            issuer-uri: https://dev-57924009.okta.com/oauth2/default
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true
management:
  security:
    enable: false